version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: excalidraw
    ports:
      - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    labels:      
      - "traefik.enable=true"  
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.hontheim.dev`) || Host(`draw.hontheim.dev`)"   
      - "traefik.http.routers.excalidraw.entrypoints=websecure"   
      # - "traefik.http.routers.excalidraw.middlewares=chain-no-auth@file"   
      - "traefik.http.routers.excalidraw.middlewares=chain-basic-auth@file"
    networks:    
      - link
     
networks: 
  link:  
    external: true

volumes:
  notused:
